### ISSUE TITLE
Java Launch Error

### ISSUE THREAD

**Issue by jakkkz** [gl91306/lunar#36] opened 2022-06-04 19:42 UTC
I keep getting java launch errors, here are my logs

[renderer.log] (https://github.com/gl91306/lunar/files/8838551/renderer.log)

**Comment by gl91306** [comment] 2022-06-06 15:30
what model pi do you have, and how much memory did you allocate to lunar client? The error says that there is insufficient memory for the application to continue, so you must have too little ram on your device or too much ram allocated to lunar client.

**Comment by WildernCyber** [comment] 2022-06-12 17:28
I got a similar message when trying to launch the new version 1.19. Does this have something to do with lwjgl?

Anyway, here is the crash report: [renderer.log](https://github.com/gl91306/lunar/files/8886354/renderer.log)

**Comment by WildernCyber** [comment] 2022-06-12 17:37
Btw, it shows this after attempting to launch, then goes back to the main lunar launch page:
![2022-06-12-183322_1280x720_scrot](https://user-images.githubusercontent.com/82512916/173245851-5ddad3a0-978b-4826-9ba0-a43e3f768e9a.png)

When I increase the RAM allocated to lunar the same thing happens. whats going on??

**Comment by gl91306** [comment] 2022-06-12 22:22
looking in the code it appears that the problem is in ```Caused by: java.lang.NullPointerException: A required function is missing: glfwInitAllocator``` I am not aware how to fix that at the moment, but ill keep trying. Does multimc work 4 u?

**Comment by WildernCyber** [comment] 2022-06-17 20:16
Ok... which java path do I select? i tried 17.0.3 but didn't work... 
![2022-06-17-211611_1280x720_scrot](https://user-images.githubusercontent.com/82512916/174395584-653f3839-e592-4ae7-bc3e-1e42d50e3c40.png)


UPDATE: Nvm, got it working

**Comment by gl91306** [comment] 2022-06-19 20:23
which java did you use for it to work?

**Comment by TheRealMesteven** [comment] 2022-07-03 02:09
Is there anymore progress on this?
I'm having the exact same null pointer exception with glfwInitAllocator only with Minecraft version 1.19 and my java copy is up to date.
(Raspberry pi 4 with 4GB memory)

**Comment by gl91306** [comment] 2022-07-04 05:10
im working on it atm

**Comment by gl91306** [comment] 2022-07-04 08:49
it should be fixed. if it is plz close this issue

**Comment by TheRealMesteven** [comment] 2022-07-04 23:25
Yep, seems to be all fixed! Nice!
Sadly I cant seem to be able to close the issue as I didn't create it :/

**Comment by gl91306** [comment] 2022-07-05 16:48
okei ill close it

**Closed as completed by gl91306** 2022-07-05 16:48 UTC
